import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';

import '../../features/calls/domain/models/call_model.dart';

class CallSignalingService {
  CallSignalingService({FirebaseFirestore? firestore})
    : _customFirestore = firestore;

  final FirebaseFirestore? _customFirestore;

  FirebaseFirestore get _firestore =>
      _customFirestore ?? FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _callsRef =>
      _firestore.collection('calls');

  bool get _isFirebaseAvailable {
    try {
      return Firebase.apps.isNotEmpty;
    } catch (_) {
      return false;
    }
  }

  /// Creates a new call document and initializes the signaling session.
  Future<String> initiateCall({
    required CallModel call,
    required RTCSessionDescription offer,
  }) async {
    if (!_isFirebaseAvailable) return call.callId;

    try {
      final docRef = call.callId.isNotEmpty
          ? _callsRef.doc(call.callId)
          : _callsRef.doc();

      final data = call.toMap();
      data['callId'] = docRef.id;
      data['offer'] = {'sdp': offer.sdp, 'type': offer.type};
      data['status'] = CallStatus.ringing.toValue();
      data['createdAt'] = FieldValue.serverTimestamp();

      await docRef.set(data);
      return docRef.id;
    } catch (e) {
      debugPrint('Error initiating call in Firestore: $e');
      rethrow;
    }
  }

  /// Streams the call document state in real-time.
  Stream<CallModel?> listenToCall(String callId) {
    if (!_isFirebaseAvailable || callId.isEmpty) {
      return const Stream.empty();
    }

    try {
      return _callsRef.doc(callId).snapshots().map((snapshot) {
        if (!snapshot.exists || snapshot.data() == null) return null;
        return CallModel.fromFirestore(snapshot);
      });
    } catch (e) {
      debugPrint('Error listening to call $callId: $e');
      return const Stream.empty();
    }
  }

  /// Pushes a caller ICE candidate to Firestore.
  Future<void> addCallerCandidate(
    String callId,
    RTCIceCandidate candidate,
  ) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef
          .doc(callId)
          .collection('callerCandidates')
          .add(candidate.toMap());
    } catch (e) {
      debugPrint('Error adding caller candidate: $e');
    }
  }

  /// Pushes a receiver ICE candidate to Firestore.
  Future<void> addReceiverCandidate(
    String callId,
    RTCIceCandidate candidate,
  ) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef
          .doc(callId)
          .collection('receiverCandidates')
          .add(candidate.toMap());
    } catch (e) {
      debugPrint('Error adding receiver candidate: $e');
    }
  }

  /// Listens to candidates generated by the caller.
  Stream<List<Map<String, dynamic>>> listenToCallerCandidates(String callId) {
    if (!_isFirebaseAvailable || callId.isEmpty) return const Stream.empty();

    try {
      return _callsRef
          .doc(callId)
          .collection('callerCandidates')
          .snapshots()
          .map((snapshot) {
            return snapshot.docs.map((doc) => doc.data()).toList();
          });
    } catch (e) {
      debugPrint('Error listening to caller candidates: $e');
      return const Stream.empty();
    }
  }

  /// Listens to candidates generated by the receiver.
  Stream<List<Map<String, dynamic>>> listenToReceiverCandidates(String callId) {
    if (!_isFirebaseAvailable || callId.isEmpty) return const Stream.empty();

    try {
      return _callsRef
          .doc(callId)
          .collection('receiverCandidates')
          .snapshots()
          .map((snapshot) {
            return snapshot.docs.map((doc) => doc.data()).toList();
          });
    } catch (e) {
      debugPrint('Error listening to receiver candidates: $e');
      return const Stream.empty();
    }
  }

  /// Accepts an incoming call and records the WebRTC answer.
  Future<void> acceptCall({
    required String callId,
    required RTCSessionDescription answer,
  }) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef.doc(callId).update({
        'status': CallStatus.accepted.toValue(),
        'answer': {'sdp': answer.sdp, 'type': answer.type},
        'startedAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('Error accepting call in Firestore: $e');
    }
  }

  /// Rejects an incoming call.
  Future<void> rejectCall(String callId) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef.doc(callId).update({
        'status': CallStatus.rejected.toValue(),
        'endedAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('Error rejecting call: $e');
    }
  }

  /// Marks a call as missed when unanswered.
  Future<void> markCallAsMissed(String callId) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef.doc(callId).update({
        'status': CallStatus.missed.toValue(),
        'endedAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('Error marking call as missed: $e');
    }
  }

  /// Ends an active call session and records duration.
  Future<void> endCall(String callId, {int durationSeconds = 0}) async {
    if (!_isFirebaseAvailable || callId.isEmpty) return;

    try {
      await _callsRef.doc(callId).update({
        'status': CallStatus.ended.toValue(),
        'endedAt': FieldValue.serverTimestamp(),
        'duration': durationSeconds,
      });
    } catch (e) {
      debugPrint('Error ending call in Firestore: $e');
    }
  }

  /// Real-time stream of ringing incoming calls for a user.
  Stream<CallModel?> listenToIncomingCalls(String currentUserId) {
    if (!_isFirebaseAvailable || currentUserId.isEmpty) {
      return const Stream.empty();
    }

    try {
      return _callsRef
          .where('receiverId', isEqualTo: currentUserId)
          .where('status', isEqualTo: CallStatus.ringing.toValue())
          .snapshots()
          .map((snapshot) {
            if (snapshot.docs.isEmpty) return null;
            // Return latest ringing call
            final doc = snapshot.docs.first;
            return CallModel.fromFirestore(doc);
          });
    } catch (e) {
      debugPrint('Error listening to incoming calls: $e');
      return const Stream.empty();
    }
  }

  /// Real-time stream of call history for a user.
  Stream<List<CallModel>> listenToCallHistory(String currentUserId) {
    if (!_isFirebaseAvailable || currentUserId.isEmpty) {
      return const Stream.empty();
    }

    try {
      return _callsRef
          .where('participants', arrayContains: currentUserId)
          .snapshots()
          .map((snapshot) {
            final calls = snapshot.docs
                .map((doc) => CallModel.fromFirestore(doc))
                .toList();
            // Client-side sort by createdAt descending to avoid composite index requirement
            calls.sort((a, b) => b.createdAt.compareTo(a.createdAt));
            return calls;
          });
    } catch (e) {
      debugPrint('Error listening to call history: $e');
      return const Stream.empty();
    }
  }
}
