// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt69IevtL0hIoksb7qUmfOA2GRJxgac20',
    appId: '1:612562007054:web:ff04b03a766d10187ab85f',
    messagingSenderId: '612562007054',
    projectId: 'convo-e3dab',
    authDomain: 'convo-e3dab.firebaseapp.com',
    storageBucket: 'convo-e3dab.firebasestorage.app',
    measurementId: 'G-RHK75T0PZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh8vFI-MBKD6Wwoq49N0utUNoFv9h7uCo',
    appId: '1:612562007054:android:f4b1a3ad7fcf8e727ab85f',
    messagingSenderId: '612562007054',
    projectId: 'convo-e3dab',
    storageBucket: 'convo-e3dab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqscpgIyzGAiWzSMDTh-O2RcCv5jmSC-Y',
    appId: '1:612562007054:ios:8b31975d41830a3b7ab85f',
    messagingSenderId: '612562007054',
    projectId: 'convo-e3dab',
    storageBucket: 'convo-e3dab.firebasestorage.app',
    iosBundleId: 'com.example.convo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt69IevtL0hIoksb7qUmfOA2GRJxgac20',
    appId: '1:612562007054:web:02553131ac70e73e7ab85f',
    messagingSenderId: '612562007054',
    projectId: 'convo-e3dab',
    authDomain: 'convo-e3dab.firebaseapp.com',
    storageBucket: 'convo-e3dab.firebasestorage.app',
    measurementId: 'G-C26S2NWFXK',
  );
}
